name: lrn
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - cmocean=2.0
  - matplotlib=3.5.1
  - networkx=2.7.1
  - notebook>=6.4.11
  - numba=0.53.1
  - numpy=1.22.3
  - pandas=1.4.3
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - tqdm=4.64.0
  - pip:
    - poisson-disc==0.2.1
    - vapory==0.1.2
